name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hallee/eslint-action@1.0.1
        env:
          HUSKY_SKIP_INSTALL: 1
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
